### ISSUE TITLE
怎么安装

### ISSUE THREAD

**Issue by jianjiandeguigui** [Yiyuiii/nonebot-plugin-moegoe#1]
D:\xx\archive\pm\pmBot>nb plugin install nonebot-plugin-moegoe
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-moegoe (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-moegoe

**Comment by Yiyuiii** [comment]
nb plugin install nonebot_plugin_moegoe
