### ISSUE TITLE
无法import PluginMetadata

### ISSUE THREAD

**Issue by B1Nnx** [Yiyuiii/nonebot-plugin-moegoe#11]
![image](https://user-images.githubusercontent.com/59869784/193468730-6bc8ad3f-c6e1-4888-ae2e-8910cc282938.png)
版本为2.0.0b2
请问是在nb2哪个版本下的

**Comment by Yiyuiii** [comment]
本插件使用了插件元信息，该特性在2.0.0b4之后才出现，建议升级nonebot包版本
具体版本信息见 https://github.com/nonebot/nonebot2/releases

我的包使用nb-cli自动安装，nb版本如下
```
nonebot-adapter-onebot (2.1.1)
nonebot2<3.0.0,>=2.0.0-beta.3 (2.0.0b5)
```
