### ISSUE TITLE
下载失败: Get "http://grouptalk.c2c.qq.com": EOF

### ISSUE THREAD

**Issue by Jerry080801** [Yiyuiii/nonebot-plugin-moegoe#14]
[2022-11-03 19:52:00] [WARNING]: 语音文件 7dbf6184f20386b0e597aaf0d998c9c5.amr
下载失败: Get "http://grouptalk.c2c.qq.com": EOF

**Comment by Yiyuiii** [comment]
我这里没有发现这个报错，可以提供一下测试示例吗
