### ISSUE TITLE
API调用失败：Client error '403 Site Disabled'

### ISSUE THREAD

**Issue by koking0** [Yiyuiii/nonebot-plugin-moegoe#15]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/45281765/202086576-3b81fefe-74b7-4286-ad43-1af9dc18ec68.png">

貌似是因为APP炸了

![image](https://user-images.githubusercontent.com/45281765/202086626-caf899af-71af-4ec5-814a-f26a684ea9e2.png)

**Comment by Yiyuiii** [comment]
确实，等待修复

**Comment by koking0** [comment]
> 确实，等待修复

啊这，之前有遇到过了么，大概需要等多久。

**Comment by Yiyuiii** [comment]
一般一两天吧

**Comment by Cvandia** [comment]
api炸了

**Comment by Yiyuiii** [comment]
api已恢复

**Comment by Super-Bramble** [comment]
大佬请问这是什么原因
![OF`B}W8L6WBIR$W0VN(O46P](https://github.com/Yiyuiii/nonebot-plugin-moegoe/assets/141409413/a4aaf935-ab0f-4a5d-905d-5c9186ff41f3)

**Comment by Yiyuiii** [comment]
这个api不公开了，可能要换一个

**Comment by Super-Bramble** [comment]
> 这个api不公开了，可能要换一个

好的，谢谢佬！
