### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by kongxiangyi88** [Yiyuiii/nonebot-plugin-moegoe#22]
![Screenshot_20230126_201829_com mapp_edit_227786401504927](https://user-images.githubusercontent.com/102857431/214833828-b7dd9367-f5a9-4743-82a6-584dd0c2e119.jpg)
![Screenshot_20230126_201743_com mapp_edit_227812796100698](https://user-images.githubusercontent.com/102857431/214833849-8c0d4f6c-4f83-47b3-b325-641c490889c4.jpg)
请问我输的是不是有什么错误，启动时报错了

**Comment by Yiyuiii** [comment]
<img width="596" alt="1674736325324" src="https://user-images.githubusercontent.com/10485632/214836350-40bd33cd-d04b-4fc0-9151-af72385438ad.png">

这两处引号修改一下

**Comment by Yiyuiii** [comment]
我修改了一下README的描述，好像产生了误解。修改后整个url还是由一对双引号包裹

**Comment by kongxiangyi88** [comment]
已解决，谢谢

**Comment by kongxiangyi88** [comment]
你好，我看见ZeroBot-Plugin那边可以实现很多角色的语音合成了，请问这个插件什么时候支持呢？

**Comment by Yiyuiii** [comment]
给个链接

**Comment by kongxiangyi88** [comment]
请问可不可以实选择输出为mp3文件，便于剪辑视频

**Comment by kongxiangyi88** [comment]
![Screenshot_20230126_211755_mark via](https://user-images.githubusercontent.com/102857431/214845254-4fc68434-e8da-497c-b2fc-e298a713aeeb.jpg)

**Comment by Yiyuiii** [comment]
可以，这两个我找时间更新一下

**Comment by Yiyuiii** [comment]
我在新的版本里加入了可以输出链接的设置，用户可以在浏览器打开链接下载音频。
ZeroBot-Plugin那边虽然README里写了新的人物，但是代码里并没有体现，他们星光的API也打不开，所以我这里还是维持原样了

**Comment by kongxiangyi88** [comment]
https://genshinvoice.top/api?speaker=[角色名]&text=[话]&format=mp3&length=1.6666666666666667&noise=[语速]&noisew=[音素长度]
我看有别人用一个语音合成网站做的，可以支持更多的角色，调节也比较细

**Comment by Yiyuiii** [comment]
我试了一下这个api，听起来好像没有这边的好，你觉得呢

**Comment by kongxiangyi88** [comment]
网上相同的也api挺多的，虽然可以进行更精细的调节，就是不知道api什么时候会寄了。 好像正常使用没有这个必要了，谢谢啦，这个iss可以关了🤞🏻

**Comment by Yiyuiii** [comment]
有个新api听起来还可以了
