### ISSUE TITLE
用yunzai的trss脚本装了这个插件后需要连续三次输入才会正确返回语音

### ISSUE THREAD

**Issue by azurcommander** [Yiyuiii/nonebot-plugin-moegoe#24]
![Y6P4~ PC0 {X_OU$P9AEK10](https://user-images.githubusercontent.com/125039039/218106202-5c704714-b0e1-4cfa-9abe-4f54ce57937a.png)
![image](https://user-images.githubusercontent.com/125039039/218106274-da0e9f71-8f0b-4ebe-8f87-31ee82afdc01.png)
否则就是会报这样的错，应该trss里没有装ffmpeg

**Comment by Yiyuiii** [comment]
这个可能是音频下载失败了，可以尝试提高url请求等待时间试试
