### ISSUE TITLE
yuanshenai api挂了

### ISSUE THREAD

**Issue by WindraiteLesd** [Yiyuiii/nonebot-plugin-moegoe#26]
genshinvoice好像还活着

**Comment by Yiyuiii** [comment]
不知道有没有购买链接

**Comment by WindraiteLesd** [comment]
> 不知道有没有购买链接

我在这里找到了有人在提供免费的ttsapi，但是不知道对方愿不愿意授权，可以商量一下？
https://gitee.com/TsaiXingyu/ttsapi-yunzai-plugin

**Comment by hnyqwq** [comment]
yuanshenai————
