### ISSUE TITLE
大佬我联网并且成功运行了但是没有在data/moegoe/ 路径下生成profile.toml文件怎么办

### ISSUE THREAD

**Issue by cchuahua** [Yiyuiii/nonebot-plugin-moegoe#28]
转换消息 [CQ:record,file=base64://PGh0bWw+PGhlYWQ+PG1ldGEgaHR0cC1lcXVpdj0icmVmcmVzaCIgY29udGVudD0iMztVUkw9aHR0cHM6Ly9zdGFybGlnaHQubnNjYy1nei5jbiIvPjx0aXRsZT7pk77mjqXkuI3lrZjlnKg8L3RpdGxlPjwvaGVhZD48Ym9keT7mgqjopoHorr/pl67nmoTpk77mjqXkuI3lrZjlnKjvvIwz56eS6ZKf5ZCO5bCG6Ieq5Yqo6Lez6L2s5Yiw6aaW6aG177yM6ams5LiK6Lez6L2s77yM6K+3PGEgaHJlZj0iaHR0cHM6Ly9zdGFybGlnaHQubnNjYy1nei5jbiIgdGFyZ2V0PSJfc2VsZiI+54K55Ye76L+Z6YeMPC9hPjwvYm9keT48L2h0bWw+,magic=,cache=,proxy=,timeout=] 到MiraiGo Element时出现错误: voice type error: text/html; charset=utf-8.
04-17 23:22:39 [INFO] nonebot_plugin_gocqhttp | [1968573103] 发送好友 908203373(908203373)  的消息: [{"type":  ... (1151693781)
04-17 23:22:39 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_moegoe) running complete
然后报错就是这个

**Comment by Yiyuiii** [comment]
这个报错应该是因为api的问题，目前应该没有免费中文api了，可以手动填网址试试
