### ISSUE TITLE
插件加载失败：IndexError: list index out of range

### ISSUE THREAD

**Issue by cj1357** [Yiyuiii/nonebot-plugin-moegoe#32]
![image](https://github.com/Yiyuiii/nonebot-plugin-moegoe/assets/40661342/4daf1481-8e90-46a5-91ad-df9daf2f9428)
![image](https://github.com/Yiyuiii/nonebot-plugin-moegoe/assets/40661342/49c5933d-99f3-4ac2-9d69-5a92903ad4ae)
是最新的配置文件里面order字段为空数组导致的吗

**Comment by Yiyuiii** [comment]
似乎是的，已更新profile了
