### ISSUE TITLE
中文字符处理

### ISSUE THREAD

**Issue by othinus001** [Yiyuiii/nonebot-plugin-moegoe#8]
测试了一下让派蒙说，输入内容包括英文的逗号句号感叹号问号，也都能返回声音，但是口音有些很奇怪，英文字母则是自动过滤了。
是否可以在处理前先替换成中文字符?

**Comment by Yiyuiii** [comment]
可以的

**Comment by othinus001** [comment]
还有0-9纯数字也可以改中文，目前会跳过纯数字

**Comment by Yiyuiii** [comment]
上述字符处理已在新版本中添加，
