### ISSUE TITLE
中日韩是不是都挂了

### ISSUE THREAD

**Issue by ElainaFanBoy** [Yiyuiii/nonebot-plugin-moegoe#9]
API调用失败：Server error '500 Internal Server Error' for url 'http://233366.proxy.nscc-gz.cn:8888?speaker=%E6%B4%BE%E8%92%99&text=%E4%BD%A0%E5%A5%BD'
For more information check: https://httpstatuses.com/500。或许输入字符不匹配语言。

**Comment by ChthollyWn** [comment]
![image](https://user-images.githubusercontent.com/85938618/187341827-65384e0e-ace1-4263-a4b7-380bc46218c2.png)
接口好像不行了

**Comment by Todysheep** [comment]
中文挂了，日韩恢复了

**Comment by ElainaFanBoy** [comment]
> 中文挂了，日韩恢复了

草，还有这事

**Comment by Stardust-minus** [comment]
前几天没有加GC导致显存经常爆炸，现在应该稳很多

**Comment by ElainaFanBoy** [comment]
> 前几天没有加GC导致显存经常爆炸，现在应该稳很多

这两天稳定多了，辛苦啦qwq
